fix

diff --git a/.github/workflows/generate-client.yml b/.github/workflows/generate-client.yml
--- a/.github/workflows/generate-client.yml
+++ b/.github/workflows/generate-client.yml
@@ -1,4 +1,4 @@
-name: Generate Client
+name: Check Frontend Client
 
 on:
   pull_request:
@@ -7,19 +7,10 @@ on:
     - synchronize
 
 jobs:
-  generate-client:
-    permissions:
-      contents: write
+  check-client:
     runs-on: ubuntu-latest
     steps:
-    # For PRs from forks
     - uses: actions/checkout@v6
-    # For PRs from the same repo
-    - uses: actions/checkout@v6
-      if: ( github.event_name != 'pull_request' || github.secret_source == 'Actions' )
-      with:
-        ref: ${{ github.head_ref }}
-        token: ${{ secrets.GITHUB_TOKEN }}
     - uses: actions/setup-node@v6
       with:
         node-version: lts/*
@@ -42,19 +33,6 @@ jobs:
         SECRET_KEY: just-for-generating-client
         POSTGRES_PASSWORD: just-for-generating-client
         FIRST_SUPERUSER_PASSWORD: just-for-generating-client
-    - name: Add changes to git
+    - name: Check client is up to date
       run: |
-        git config --local user.email "github-actions@github.com"
-        git config --local user.name "github-actions"
-        git add frontend/src/client
-    # Same repo PRs
-    - name: Push changes
-      if: ( github.event_name != 'pull_request' || github.secret_source == 'Actions' )
-      run: |
-        git diff --staged --quiet || git commit -m "✨ Autogenerate frontend client"
-        git push
-    # Fork PRs
-    - name: Check changes
-      if: ( github.event_name == 'pull_request' && github.secret_source != 'Actions' )
-      run: |
-        git diff --staged --quiet || (echo "Changes detected in generated client, run scripts/generate-client.sh and commit the changes" && exit 1)
+        git diff --exit-code frontend/src/client || (echo "::error::Frontend client is out of date. Run 'scripts/generate-client.sh' and commit the changes." && exit 1)
